/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ApiScanPantryRouteImport } from './routes/api/scan-pantry'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as CookRecipeIdRouteImport } from './routes/cook.$recipeId'
import { Route as RecipesIndexRouteImport } from './routes/recipes.index'
import { Route as RecipesRecipeIdRouteImport } from './routes/recipes.$recipeId'
import { Route as ApiPublicRecipeImageRouteImport } from './routes/api/public/recipe-image'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanPantryRoute = ApiScanPantryRouteImport.update({
  id: '/api/scan-pantry',
  path: '/api/scan-pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CookRecipeIdRoute = CookRecipeIdRouteImport.update({
  id: '/cook/$recipeId',
  path: '/cook/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIndexRoute = RecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRecipeIdRoute = RecipesRecipeIdRouteImport.update({
  id: '/recipes/$recipeId',
  path: '/recipes/$recipeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecipeImageRoute = ApiPublicRecipeImageRouteImport.update({
  id: '/api/public/recipe-image',
  path: '/api/public/recipe-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/scan-pantry': typeof ApiScanPantryRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/cook/$recipeId': typeof CookRecipeIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/public/recipe-image': typeof ApiPublicRecipeImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/scan-pantry': typeof ApiScanPantryRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/cook/$recipeId': typeof CookRecipeIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes': typeof RecipesIndexRoute
  '/api/public/recipe-image': typeof ApiPublicRecipeImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/api/scan-pantry': typeof ApiScanPantryRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/cook/$recipeId': typeof CookRecipeIdRoute
  '/recipes/$recipeId': typeof RecipesRecipeIdRoute
  '/recipes/': typeof RecipesIndexRoute
  '/api/public/recipe-image': typeof ApiPublicRecipeImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/scan-pantry'
    | '/api/speak'
    | '/api/transcribe'
    | '/cook/$recipeId'
    | '/recipes/$recipeId'
    | '/recipes/'
    | '/api/public/recipe-image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/scan-pantry'
    | '/api/speak'
    | '/api/transcribe'
    | '/cook/$recipeId'
    | '/recipes/$recipeId'
    | '/recipes'
    | '/api/public/recipe-image'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/api/scan-pantry'
    | '/api/speak'
    | '/api/transcribe'
    | '/cook/$recipeId'
    | '/recipes/$recipeId'
    | '/recipes/'
    | '/api/public/recipe-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiScanPantryRoute: typeof ApiScanPantryRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  CookRecipeIdRoute: typeof CookRecipeIdRoute
  RecipesRecipeIdRoute: typeof RecipesRecipeIdRoute
  RecipesIndexRoute: typeof RecipesIndexRoute
  ApiPublicRecipeImageRoute: typeof ApiPublicRecipeImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan-pantry': {
      id: '/api/scan-pantry'
      path: '/api/scan-pantry'
      fullPath: '/api/scan-pantry'
      preLoaderRoute: typeof ApiScanPantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cook/$recipeId': {
      id: '/cook/$recipeId'
      path: '/cook/$recipeId'
      fullPath: '/cook/$recipeId'
      preLoaderRoute: typeof CookRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/': {
      id: '/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof RecipesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$recipeId': {
      id: '/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/recipes/$recipeId'
      preLoaderRoute: typeof RecipesRecipeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recipe-image': {
      id: '/api/public/recipe-image'
      path: '/api/public/recipe-image'
      fullPath: '/api/public/recipe-image'
      preLoaderRoute: typeof ApiPublicRecipeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiScanPantryRoute: ApiScanPantryRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  CookRecipeIdRoute: CookRecipeIdRoute,
  RecipesRecipeIdRoute: RecipesRecipeIdRoute,
  RecipesIndexRoute: RecipesIndexRoute,
  ApiPublicRecipeImageRoute: ApiPublicRecipeImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
